### ISSUE TITLE
Need for globally unique IDs

### ISSUE THREAD

**Issue by dugauthier** [roq-messaging/RoQ#103]
A guid should be assigned to new queues upon creation and used afterwards to reffer to this queue without leaving place for confusion.

Currently (at least in the web-api of the backend), the queue name is used as ID.

The ID could be generated based on the host and the queue name for instance.

**Comment by sskhiri** [comment]
Actually, from RoQ core viewpoint I am not sure it is necessary, since the client must use the queue name to target the queue he wants to create or to connect to send or rcv messages. That is also the case in JMS:

``` Java
 // get the initial context
InitialContext ctx = new InitialContext();

// lookup the queue object
Queue queue = (Queue) ctx.lookup("queue/queue0");
```

In this case, queue0 is the name. Since the queue name must be unique in order to avoid any issue, the name is used as key. We use the same approach in RoQ:

``` Java
//1. Create with the factory, create the connection
String configServerAddress = "192.23.25.25";
IRoQConnectionFactory factory= new RoQonnectionFactory(configServerAddress );
//Create a Q connection on the logical queue name queue1 with the filter key sabri.
IRoQSubscriberConnection subConnection = factory.createRoQSubscriberConnection("queue1","sabri");
```

Going further, in the current version the same queue name cannot be used even in different hosts.
Now, from the back-end viewpoint is up to you, if you see any reasons to add a guiID that is OK.

**Comment by dugauthier** [comment]
Actually, my main problem is to have a uid chosen by the user. The behavior of the REST proxy of ExtJS is, whenever a uid is not null (which is the case when we choose a name) to use the element URL rather than the collection URL. It thus POST a request to a the URL /queue/queuename  rather than to the /queue URL. The following SO post explains the exact problem I'm facing.
http://stackoverflow.com/questions/12488396/extjs4-model-with-user-defined-id

Maybe the best way to handle this it to let roq-backend generate the ID and use the name choosen by the user as ID. I'd thus have attributes ID, Name, Host, Status, ... would send everything except ID and would receive back the same tupple with Name copied as ID or an error if the name is already used.
The other option is to mess with the URL mapping of the REST proxy. Maybe not the cleanest way to handle it..

**Comment by sskhiri** [comment]
Is it still an issue ? Can you elaborate.
