### ISSUE TITLE
Scalable and elastic ZMonitor

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#11]
Today the monitoring is centralised, it must be scalable according to the number of events. We need to:
- Define KPI for the elasticity
- Define an elastic policy architecture
- Define an HA policy

**Comment by cduverne** [comment]
KPIs definition :
- I'd suggest to use the number of ZExchanges monitored during a time period for the scale-in/out of the ZMonitor
  - If a ZMonitor handles more than x ZExchanges during more than y seconds -> Scale out !
  - If a ZMonitor handles less than z ZExchanges during more than i seconds -> Scale in !

To define the unknowns, how could we perform some kind of perf test on the ZMonitor ? 
The Scenario could be :
    - Send 10 request of ZEchanges creation/30 secondes to the system
    - Measure the time for creation of the new ZExchanges

This is quite cloudy, but seems simple for a beginning.

**Comment by cduverne** [comment]
HA Policy :

This could be handled via the ZooKeeper study (issue #26)

Since the state and configuration of the ZMonitor might be recorded in ZooKeeper.

We still need to know when the ZMonitor isn't responding, or working in abnormal mode.

I'd suggest then to add a "ZMonitor Monitoring" in each ZMonitor of a pool, which would check the state of the other ZMonitor.

This means that we should have at least 2 ZMonitors in a pool, a master and a slave (which could be idle)

Feedbacks are more than welcome :)

**Comment by sskhiri** [comment]
OK, from the monitor implementation, this means that we need to share the data handled by the monitor between the master and the slave.
For doing that we can either use:
- a cache (as the cache feature of INFINISPAN or memcache ) and to configure a sync policy (sync or async)
- implementing oursleve a configuration socket that update every monitor data

In addition we need to modify the monitor in order to let him inactive (socket closed for instance).

Finally, coming back to your suggestion don't you think that Zookeeper can play the role of the Monitor Monitoring ? I think that it should have some feature to detect that a node dies, isn't it ?

**Comment by cduverne** [comment]
Still learning about ZooKeeper, I'll keep you posted :)
