### ISSUE TITLE
Adding a job on the CI for the master branch

### ISSUE THREAD

**Issue by jbruggem** [roq-messaging/RoQ#122]
In order to build the stable release. Should be triggered by push on master. Linked to #119

**Comment by jbruggem** [comment]
Done. There are now two jobs in the CI, RoQStable and RoQNightly.

We might need to update some links in the documentation or the web site.

**Comment by jbruggem** [comment]
@sskhiri some tests are failing. It might be due to a recent update on the server to Java 7.

**Comment by sskhiri** [comment]
I am not sure it is about java. I think it is because the two build are running the same set of test more or less in the same time. As the tests open sockets and launch processes, the socket are found already in use. I do not think it is a big deal, we need to cleanly stop the current test, manually launch the stable build. I will try. 
@cduverne GimmeRoQ.sh must be updted with the new job names in the latest.tar file.

**Comment by sskhiri** [comment]
It works nice! We just need to be sure that the stable build is not automatically triggered. In this case we can ensure that the 2 jobs are not running ins the same time.

**Comment by sskhiri** [comment]
@jbruggem There is somthing strange with the CI, it seems that it does not maintain the history build anymore. This morning, There no build at all ! I relaunched one manually. Can you investigate ?
