### ISSUE TITLE
The key filtering code when subscribing to a queue seems wrong.

### ISSUE THREAD

**Issue by jbruggem** [roq-messaging/RoQ#146]
So, I'm not really sure on this one, but I don't understand how this is supposed to work. 

The code handling a new subscription to a queue seems wrong. The key is used to filter out the monitor channel:
https://github.com/roq-messaging/RoQ/blob/master/roq-core/src/main/java/org/roqmessaging/core/SubscriberConnectionManager.java?source=cc#L87
While when subscribing to the exchanges, the filtering queue used is empty:
https://github.com/roq-messaging/RoQ/blob/master/roq-core/src/main/java/org/roqmessaging/core/SubscriberConnectionManager.java?source=cc#L148

I would have expected the contrary. Is this really a bug? Otherwise, does somebody have an explanation?

**Comment by sskhiri** [comment]
When the subscritpion key is empty, that means that you subscribe to all messages whatever the key. This must be the right behavior for the Exchange since it does not have any information about key or routing destination for a key. In the other hand Subs connection manager has to subscribe according to the client key specified by the consumer client. 
So it is not a bug. Does it answer your question ?

**Comment by jbruggem** [comment]
Well, not really: The bits of code I linked are both part of the Subs Connection Manager and not part of the Exchange.

Correct me if I'm wrong:
- **The first link is where the SubsManager subscribes to the monitor channel.**
  => I would think he should receive _all_ messages, thus would not need a filtering key -- and yet he has one.
- **The second link is where the SubsManager subscribes to all the exchanges handling his queue.**
  => I would guess that it _needs_ a filtering key, to only transmit the messages that actually match his key. Yet it subscribes to every exchange without a key.
