### ISSUE TITLE
Topology management: Zookeeper study

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#26]
We need to maintain the topological information at 2 levels:
- MonitorManager: we need to know for each logical queue the set of exchanges and its monitor
- Host: we need to know the set of exchanges and monitor + their ports

Can Zookeeper be used for that purpose ?

**Comment by cduverne** [comment]
After hours of research in the huge spaghetti plate formed by the documentation about Zookeeper, I finally found an easy-to-understand summary of Zookeeper :

http://developer.yahoo.com/hadoop/tutorial/module6.html

From my little programming point of view, I understood that Zookeeper is able to store anything since it's less than 1MB big.

For RoQ purpose we need to store lists of exchange etc... this should be well formatted (XML ?) in order to let the exchanges/monitor understand the topology, and Zookeeper will be only be the holder of the information but not the manager.

We have to maintain a map of the RoQ architecture in the Zookeeper infra, such as :

`<logQueue>`
`<exchange>`
`<ip>`192.168.0.222`</ip>`
`<port>`12`</port>`
`</exchange>`

`<exchange>`
`<ip>`192.168.0.222`</ip>`
`<port>`12`</port>`
`</exchange>`
`</logQueue>`

etc...

I need to set up kind of a PoC to understand how Zk is concreatly working, but if we have someone who is able to explain it deeper I would be more than happy to meet him/her :-)

**Comment by cduverne** [comment]
BTW, since we don't want Zookeeper to be a SPOF, we need to have Zookeeper usable on a cluster of machines.

Zk is handling quite easily the HA and synchronism between nodes.

**Comment by cduverne** [comment]
Regarding the ongoing study on Infinispan, I would recommend to trash ZooKeeper :)

In order to have a unity between languages, ZooKeeper is a server for which we should have to learn new commands etc...

Infinispan is a java software, which could make our programming job easier.
