### ISSUE TITLE
Study of INFINISPAN for the global config Manager

### ISSUE THREAD

**Issue by sskhiri** [roq-messaging/RoQ#35]
At the end of Porshe ... the legend, we will have a global config manager that handle the location of each monitor of each logical queue. In order to distribute this information it would be usefull to consider a data grid such as INFINISPAN. In addition as the Global config manager uses a request socket (as a server) to serve configuration request, the ZMQ layer could even serve as Load balancer between different instances of the config manager sharing the data grid.
The objectives of this study are:
- Defining whether it could be used for distributing the config manager
- Defining how the ZMQ can be used as LB among different instances of Config manager (quite straight forward)
- Cost estimation
- Alternatives

**Comment by cduverne** [comment]
On Infinispan side, it looks quite clearier to find easily-understandable documentation (https://docs.jboss.org/author/display/ISPN/Getting+Started+Guide#GettingStartedGuide-DownloadingandinstallingInfinispan)

1/ Distribution of the config manager

Infinispan can cache the topology and distribute it to all his nodes.
Each item is cached as an object and doesn't have to be in a specific format, so this allow us to use any file format for the topology registration.

When Infinispan is set up on a node (few steps actually) you just have to run this command (sample) :

"java -cp target/classes/:target/dependency/\* org.infinispan.quickstart.clusteredcache.distribution.Node0"

I won't paste the documentation here, because it's really clear, and the usage of Infinispan seems really easy, fews lines offer the caching features.

2/ Load balancing by ZMQ

TODO

3/ Cost estimation

Infinispan is free, under LGPL licence
Can't tell the effort to implement it in RoQ's actual state, but I don't think that it's huge.

4/ Alternatives

memcached, varnish : Those are caching servers to be setup on a client and called by each client, which could be a SPOF

I didn't investigate this track deeper.

**Comment by sskhiri** [comment]
# Clarification

"Defining how the ZMQ can be used as LB among different instances of Config manager (quite straight forward)"
Today, the configuration manager starts at a central place with one IP address:port. This location is the only information that must be known by the RoQ element when they start (the HostConfigManager, Management Server, Logical Queue Factory, etc.)
If we go on INFINISPAN for the Config Server, this means that we will end up with several location to be known. Then the question is What about the re-factoring ?
1. do all RoQ element need to consider a list of address ? and then the request to this list must use the ZMQ load  balancing feature? (in ZMQ you can connect multiple host and ZMQ will automatically load balance the request for you) how do we manage the dynamical aspects when new Config Server are spawned ? or 
2. do we keep 1 address that will be a RoQ element that will load balance between Config Server Instances, then we need to implement a self registry mechanism (not complex already done for the Host Config server that self register on the global configration)

**Comment by cduverne** [comment]
Infinispan is accessible through the following documentation :

Geetting Started : https://docs.jboss.org/author/display/ISPN/Getting+Started+Guide

Maven : https://docs.jboss.org/author/display/ISPN/Contributing+to+Infinispan#ContributingtoInfinispan-BuildingInfinispan

Enjoy ! :p

**Comment by sskhiri** [comment]
The infinispan cluster for replication of the GCM state works now !! @cduverne the eviction was the main reason

```
  <namedCache name="roqcache">
<!--       <expiration lifespan="20000" maxIdle="500" /> -->
      <clustering mode="replicated">
      <sync/>
      </clustering>
   </namedCache>
```

Now it works. Next step: configuring the logs of infinispan, if possible as a property of the GCM, and sharing the state using the RoQCaheManager.

**Comment by cduverne** [comment]
That's why your the code master ! :p Congratulations.

If I remember well we suggest that the expiration could be a problem...

**Comment by sskhiri** [comment]
BTW, there was also an issue with the Jgroups-tcp.xml where we forgot to bind an address in the TCP tag. Now on the last version I commited, the trace is merged with our RoQ log4j property file. We can start the integration within the architecture and re-thinking the way the GCM act with the other components.

**Comment by sskhiri** [comment]
@cduverne before closing the issue, can find a way to listen any new cluster members joining the cache cluster?

**Comment by cduverne** [comment]
Add a generic listener to permit the event catching when a new member is coming online or offline...
